# Generated by Django 6.0.8 on 2026-08-25 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='Question_text',
            new_name='question',
        ),
        migrations.AlterField(
            model_name='question',
            name='technology',
            field=models.CharField(max_length=100),
        ),
    ]
